client_id = "1ab6ad2a7b925816f71cf34766518a39"
name = "cod-shield"
application_url = "https://cod-shild-app-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cod-shield-dev.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/uninstalled", "orders/create", "orders/updated" ]

[access_scopes]
scopes = "read_fulfillments,write_fulfillments,read_orders,write_orders,customer_read_orders,customer_write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://cod-shild-app-production.up.railway.app/auth/callback"
]

[pos]
embedded = false